# Generated by Django 4.2.16 on 2026-06-19 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField(default=0, verbose_name='Tổng tiền')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên tạo')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên món')),
                ('price', models.IntegerField(verbose_name='Giá tiền')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Hình ảnh')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe_app.category', verbose_name='Danh mục')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Số lượng')),
                ('price', models.IntegerField(verbose_name='Giá tại thời điểm bán')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe_app.order', verbose_name='Hóa đơn')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe_app.product', verbose_name='Món uống')),
            ],
        ),
    ]
