# Generated by Django 5.0.14 on 2026-07-07 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ví dụ: 360ml, 500ml, 700ml, Standard...', max_length=50)),
                ('price', models.IntegerField(help_text='Giá tiền cho size này')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='cafe_app.product')),
            ],
        ),
    ]
